import "../styles/globals.css";
import { font } from "./font";
import Header from "@/components/Header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
  variable: "--font-poppins"
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header />
        <div className="main p-5">{children}</div>
      </body>
    </html>
  );
}
